# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("https://armcrm-dev.test.gosuslugi.ru/login")
    self.driver.set_window_size(1200, 1200)
    self.driver.find_element(By.ID, "username").send_keys("api")
    self.driver.find_element(By.ID, "password").send_keys("usetech@")
    element = self.driver.find_element(By.CSS_SELECTOR, ".styles__button__2b5Jq")
    self.driver.find_element(By.CSS_SELECTOR, ".styles__button__2b5Jq").click()
    time.sleep(2)
    #до этого момента все ок, как закончить?
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-contained")
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-contained").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("081222")
    time.sleep(1)
    self.driver.find_element(By.ID, "description").click()
    self.driver.find_element(By.ID, "description").send_keys("0812")
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-root:nth-child(3)").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    element = self.driver.find_element(By.CSS_SELECTOR, ".user-menu-module__user-name-text__2_L8L")
    self.driver.find_element(By.CSS_SELECTOR, ".user-menu-module__user-name-text__2_L8L").click()
    #попытка 2
    time.sleep(2)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    self.driver.find_element(By.CSS_SELECTOR, ".user-menu-module__user-info-role-button__3I6l_").click()
    time.sleep(2)
