# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.method_name1()
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(1) > .MuiTableCell-root:nth-child(2) > div > span").click()
    self.driver.close()

  def method_name1(self, i=1936, height=1056):
    self.driver.get(
      "https://armcrm-dev.test.gosuslugi.ru/target-audiences?status=ACTIVE&status=DRAFT&ordering=-updated_at")
    self.driver.set_window_size(i, height)
  
