# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test0512():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_0512(self):
    self.driver.get("https://armcrm-dev.test.gosuslugi.ru/login")
    self.driver.set_window_size(518, 98)
    self.driver.find_element(By.ID, "username").send_keys("api")
    self.driver.find_element(By.ID, "password").send_keys("usetech@")
    self.driver.find_element(By.CSS_SELECTOR, ".styles__button__2b5Jq").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-contained")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-contained").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("123546576")
    self.driver.find_element(By.ID, "description").click()
    self.driver.find_element(By.ID, "description").send_keys("5кне56н7567")
    self.driver.find_element(By.CSS_SELECTOR, ".css-dmxury-placeholder").click()
    self.driver.find_element(By.ID, "react-select-4-option-0").click()
    self.driver.find_element(By.CSS_SELECTOR, ".MuiGrid-grid-lg-5").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-root:nth-child(3)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-root:nth-child(3)").click()
    self.driver.execute_script("window.scrollTo(0,0)")
  
