# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestChange():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_change(self):
    self.driver.get("https://armcrm-dev.test.gosuslugi.ru/target-audiences?status=ACTIVE&status=DRAFT&ordering=-updated_at")
    self.driver.set_window_size(1936, 1056)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(1) .styles__actions-icons__2Yqi9 > .MuiButtonBase-root:nth-child(1) path")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR,
                             ".MuiTableRow-root:nth-child(1) .styles__actions-icons__2Yqi9 > .MuiButtonBase-root:nth-child(1) path").click()
    self.driver.find_element(By.CSS_SELECTOR, ".styles__content__sdWL0").click()
    self.driver.find_element(By.ID, "name").send_keys("09122222")
    self.driver.find_element(By.ID, "description").click()
    self.driver.find_element(By.ID, "description").send_keys("6514")
    self.driver.find_element(By.CSS_SELECTOR, ".css-dmxury-placeholder").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,0)")

    self.driver.find_element(By.ID, "react-select-4-option-12").click()
    self.driver.find_element(By.CSS_SELECTOR, ".MuiGrid-grid-lg-5").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-root:nth-child(3)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-root:nth-child(3)").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(9) .styles__actions-icons__2Yqi9").click()
  
