# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


# рабочий тест
class Test0812():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_untitled(self):
        self.link_acrm()
        self.login("devstigneeva", "fWd9iGZz")
        time.sleep(2)
        self.create_audiences("0812", "0812")
        # нужна проверка, что выполнен переход на страницу к перечню ца
        time.sleep(2)
        self.open_sidebar()
        time.sleep(2)
        self.logout()
        time.sleep(2)


    # выход из системы
    def logout(self):
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        self.driver.find_element(By.CSS_SELECTOR, ".user-menu-module__user-info-role-button__3I6l_").click()

    # открытие боковой панели с данными пользователя
    def open_sidebar(self):
        self.driver.execute_script("window.scrollTo(0,0)")
        element = self.driver.find_element(By.CSS_SELECTOR, ".user-menu-module__user-name-text__2_L8L")
        self.driver.find_element(By.CSS_SELECTOR, ".user-menu-module__user-name-text__2_L8L").click()

    # создание ЦА
    # нужно добавить также добавление тегов
    # создать отдельные методы с деактивацией чекбокса, со сменой режима, добавление правил
    def create_audiences(self, name_audience, description_audience):
        element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-contained")
        self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-contained").click()
        time.sleep(1)
        self.driver.find_element(By.ID, "name").click()
        self.driver.find_element(By.ID, "name").send_keys(name_audience)
        time.sleep(1)
        self.driver.find_element(By.ID, "description").click()
        self.driver.find_element(By.ID, "description").send_keys(description_audience)
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-root:nth-child(3)").click()

    # авторизация
    def login(self, username, password):
        self.driver.find_element(By.ID, "username").send_keys(username)
        self.driver.find_element(By.ID, "password").send_keys(password)
        element = self.driver.find_element(By.CSS_SELECTOR, ".styles__button__2b5Jq")
        self.driver.find_element(By.CSS_SELECTOR, ".styles__button__2b5Jq").click()

    # настройки браузера и ссылки
    def link_acrm(self):
        self.driver.get("https://armcrm-dev.test.gosuslugi.ru/login")
        self.driver.set_window_size(1920, 1080)