# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from application import Application

#фикстура
@pytest.fixture()
def app(request):
    fixture = Application()
    request.addfinalizer(fixture.destroy)
    return fixture


# рабочий тест
def test_untitled(app):
    app.link_acrm()
    app.login("devstigneeva", "fWd9iGZz")
    time.sleep(2)
    app.create_audiences("091222", "0912")
    # нужна проверка, что выполнен переход на страницу к перечню ца
    time.sleep(2)
    app.open_sidebar()
    time.sleep(2)
    app.logout()
    time.sleep(2)
