# Generated by Selenium IDE
import pytest
import time
from fixture.application import Application

#фикстура
@pytest.fixture()
def app(request):
    fixture = Application()
    request.addfinalizer(fixture.destroy)
    return fixture


# рабочий тест
def test_untitled(app):
    app.link_acrm()
    app.session.login("devstigneeva", "fWd9iGZz")
    time.sleep(2)
    app.audience.create("091222", "0912")
    # нужна проверка, что выполнен переход на страницу к перечню ца
    time.sleep(2)
    app.open_sidebar()
    time.sleep(2)
    app.session.logout()
    time.sleep(2)
